[package]
name = "parse-chunk-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
crossbeam = "0.8.4"
lazy_static = "1.5.0"
memchr = "2.7.6"
quick-xml = "0.39.0"
rayon = "1.11.0"
regex = "1.12.2"
